[package]
resolver = "2"
authors = ["dheijl <danny.heijl@telenet.be>"]
edition = "2021"
name = "swyh-rs"
version = "1.4.3"
description = "Stream What You Hear written in Rust"
license = "MIT"
repository = "https://github.com/dheijl/swyh-rs/"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[dependencies]
bitflags = "1.3.2"
cpal = "0.13.5"
crossbeam-channel = "0.5.6"
dirs = "4.0.0"
flac-bound = { version = "0.3.0", default-features = false, features = [
    "libflac-noogg",
] }
fltk = { version = "1.3.12", features = ["use-ninja"] }
#fltk-flow = "0.1.4"
htmlescape = "0.3.1"
if-addrs = "0.7.0"
log = { version = "0.4.17", features = [
    "max_level_trace",
    "release_max_level_debug",
    "serde",
] }
once_cell = "1.13.0"
parking_lot = "0.12.1"
serde = { version = "1.0.143", features = ["derive"] }
simplelog = "0.12.0"
rand = "0.8.5"
strfmt = "0.2.1"
stringreader = "0.1.1"
tiny_http = "0.11.0"
toml = "0.5.9"
ureq = { version = "2.5.0", features = ["charset"] }
url = "2.2.2"
xml-rs = "0.8.4"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "std"] }
winres = "0.1.12"
[target.'cfg(unix)'.dependencies]
libc = "0.2.127"

[patch.crates-io]
#fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
#tiny_http = { git = "https://github.com/tiny-http/tiny-http" }
#cpal = { git = "https://github.com/RustAudio/cpal" }
#flac-bound = { git = "https://github.com/dheijl/flac-bound" }
#flac-bound = { git = "https://github.com/nabijaczleweli/flac-bound" }
